### ISSUE TITLE
Multiple commands produce xx/Assets.car

### ISSUE THREAD

**Issue by iDylanK** [voxeet/voxeet-uxkit-ios#12]
**Describe the bug**

When using the 'New Build System' to build an application with the VoxeetUXKit (added as a Pod) the error 'Multiple commands produce xx/Assets.car' occurs. 

**Steps to Reproduce the Problem**

  1. Open a project inside Xcode 12
  2. Add VoxeetUXKit pod. 
  3. Build

**Reference**
[https://dev.to/kylefoo/xcode-12-new-build-system-warns-multiple-commands-produce-assets-car-56im](https://dev.to/kylefoo/xcode-12-new-build-system-warns-multiple-commands-produce-assets-car-56im)

**Comment by VTCoco** [comment]
Hello,

Replacing `resources` with `resource_bundles` isn't enough after our tests, what are your pods dependencies so we can reproduce the 'Multiple commands produce xx/Assets.car' please?

**Comment by iDylanK** [comment]
Hi, thank you for checking it out this fast. 

My dependencies:
  - Alamofire
  - Charts
  - Firebase/Messaging
  - LanguageManager-iOS
  - Sentry
  - SideMenu
  - SwiftKeychainWrapper
  - SwiftyJSON
  - UICircularProgressRing
  - VoxeetSDK
  - VoxeetUXKit
  - YoutubePlayer-in-WKWebView

After removing VoxeetUXKit the issue is gone.

**Comment by VTCoco** [comment]
We tried with:
```
  pod 'Alamofire', '~> 5.2'
  pod 'Charts'
  pod 'SideMenu'
  pod "YoutubePlayer-in-WKWebView", "~> 0.3.0"
  pod 'LanguageManager-iOS'
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '6.2.0'
  pod 'SwiftyJSON', '~> 4.0'
```
and importing them:
```
import UIKit
import VoxeetUXKit
import VoxeetSDK
import Alamofire
import Charts
import SideMenu
import SwiftyJSON
import LanguageManager_iOS
import Sentry
```

But we aren't able to reproduce `'Multiple commands produce xx/Assets.car'`. Is it complicated for you to locate between your dependencies which is in conflict with VoxeetUXKit by commenting them one by one?

This multiple commands error is a build issue right? What is your Xcode and cocoapods version?

**Comment by iDylanK** [comment]
I found out what the problem is. It's with SDWebimage, as it comes installed with VoxeetUXKit. SDWebImage does not define modules, so it's not possible yet to use it with swift static libraries. (commeting use_frameworks! inside the Podfile). Thanks for your help!
