### ISSUE TITLE
Problem with CallKit, PushKit and joining a conference

### ISSUE THREAD

**Issue by iDylanK** [voxeet/voxeet-uxkit-ios#13]
Hey! For the past few days I'm trying to setup conference calling using CallKit and PushKit. In my AppDelegate I have among other things:

`
VoxeetUXKit.shared.initialize()
VoxeetSDK.shared.notification.push.type = .callKit
`

When I receive a PushKit notification I use `displayIncomingCall` to notify CallKit and at the same time asynchronously get a Voxeet auth token, call `VoxeetSDK.shared.session.open()` and fetch the created conference (by the sender) using `VoxeetSDK.shared.conference.fetch(conferenceID: conference)`. 

When the receiver answers the call later on, `VoxeetSDK.shared.conference.join` is called. The problem now is that when the conference is joined. my delegate function `func provider(_ provider: CXProvider, perform action: CXEndCallAction)` is called. I really can't figure out why. Do you have any idea what I could by doing wrong?

**Comment by iDylanK** [comment]
@VTCoco is it a bug or am I doing sth wrong?

**Comment by iDylanK** [comment]
Thank you for your help. I tried both ways now, using the Voxeet's Callkit instance and my own. When using Voxeet's one, getting called is not working when the application is in the background or terminated state. The app crashes and shows: 

'Apps receving VoIP pushes must post an incoming call (via CallKit or IncomingCallNotifications) in the same run loop as   pushRegistry:didReceiveIncomingPushWithPayload:forType:[withCompletionHandler:] without delay.'

It does work when the app is in foreground.

**Comment by iDylanK** [comment]
I still can't figure it out @VTCoco . Is it possible that the Voxeet library is not calling the required 'reportNewIncomingCall' function?

**Comment by VTCoco** [comment]
We are making sure to call `reportNewIncomingCall` on our side because it's mandatory since iOS 13. Do you have the same log when you implement your custom CallKit (will need `VoxeetSDK.shared.notification.push.type = .none`)?

Do you call `VoxeetSDK.shared.session.open()` at `func pushRegistry(_ registry: PKPushRegistry, didReceiveIncomingPushWith payload: PKPushPayload, for type: PKPushType, completion: @escaping () -> Void)`?

**Comment by iDylanK** [comment]
When I'm implementing my own with `VoxeetSDK.shared.notification.push.type = .none` it is working when I call `reportNewIncomingCall`. But this implementation gives me other problems down the road, so I prefer to use the Voxeet's one. 

So I'm using `VoxeetSDK.shared.notification.push.type = .callKit`

Is it mandatory to implement the PKPushRegistryDelegate myself? It doesn't seem to make any difference.
When I do implement it, it looks like:

`
extension AppDelegate: PKPushRegistryDelegate {
    func pushRegistry(_ registry: PKPushRegistry, didUpdate pushCredentials: PKPushCredentials, for type: PKPushType) {
        VoxeetSDK.shared.notification.push.pushRegistry(registry, didUpdate: pushCredentials, for: type)
    }

    func pushRegistry(_ registry: PKPushRegistry, didInvalidatePushTokenFor type: PKPushType) {
        VoxeetSDK.shared.notification.push.pushRegistry(registry, didInvalidatePushTokenFor: type)
    }

    func pushRegistry(_ registry: PKPushRegistry, didReceiveIncomingPushWith payload: PKPushPayload, for type: PKPushType, completion: @escaping () -> Void) {
        let info = VTParticipantInfo(
                               externalID: "XXX", name: "YYYY", avatarURL: "")
        VoxeetSDK.shared.session.open(info: info) { _ in }
        VoxeetSDK.shared.notification.push.pushRegistry(registry, didReceiveIncomingPushWith: payload, for: type, completion: completion)
        }

    }
}
`

With global ` var voipRegistry: PKPushRegistry!`

and inside the didFinishLaunchingWithOptions;

`
self.voipRegistry = PKPushRegistry(queue: nil)
self.voipRegistry.delegate = self
self.voipRegistry.desiredPushTypes = [.voIP]
`

**Comment by VTCoco** [comment]
If you are using our CallKit solution make sure to not use the `pushRegistry.delegate = self` because the Voxeet SDK will lost the delegate response and then yes the `reportNewIncomingCall ` will not be called. Can this help you?

So no, it's not recommended to implement `PKPushRegistryDelegate` if you are using `VoxeetSDK.shared.notification.push.type = .callKit`.

**Comment by iDylanK** [comment]
That's what I had before, but it raises the exact same problem.

The only Voxeet code in my AppDelegate:

```
VoxeetSDK.shared.initialize(consumerKey: "XXXX", consumerSecret: "YYY")
VoxeetSDK.shared.notification.push.type = .callKit
VoxeetSDK.shared.conference.defaultVideo = true
VoxeetSDK.shared.conference.defaultBuiltInSpeaker = true
VoxeetUXKit.shared.initialize()
```

**Comment by iDylanK** [comment]
@VTCoco I still get the same problem. I tried everything. Any ideas ? Can it be related to my UNUserNotificationCenter delegate used for other push notifications ?

**Comment by VTCoco** [comment]
No I don't think UNUserNotificationCenter is related or conflicting with PushKit.
But all PushKit methods are execute in a specific thread, have you tried to create and join your conference in the main thread?

**Comment by iDylanK** [comment]
I'm not creating and joining the conference myself now... It's done by the Voxeet SDK.

So the only code in my application did finish function is:

```
VoxeetSDK.shared.initialize(consumerKey: "XXXX", consumerSecret: "YYY")
VoxeetSDK.shared.notification.push.type = .callKit
VoxeetSDK.shared.conference.defaultVideo = true
VoxeetSDK.shared.conference.defaultBuiltInSpeaker = true
VoxeetUXKit.shared.initialize()

let info = VTParticipantInfo(externalID: "XXX", name: "YYYY", avatarURL: "")
VoxeetSDK.shared.session.open(info: info) { _ in }
```

Getting called still only works when the app is in foreground. I really don't know anymore...

**Comment by iDylanK** [comment]
<img width="1920" alt="voxeet_pushkit_example" src="https://user-images.githubusercontent.com/18072630/112524155-c804b400-8d9f-11eb-9ec7-d924a1b6e936.png">

@VTCoco

**Comment by VTCoco** [comment]
Thank you for sharing your crash.
What is the VoxeetSDK and VoxeetUXKit version used?
What is the device model and OS?
Are you reproducing it with our sample app? https://github.com/voxeet/voxeet-uxkit-ios/tree/master/Sample (don't forget to change app **keys/secret** in the AppDelegate.swift and the **Bundle Identifier** to match with your APNs certificate)

In **Signing & Capabilities**, check if "Audio, AirPlay, and Picture in Picture" and "Voice over IP" are properly selected in **Background Modes**. Also check if **Push Notifications** is also present.

After retesting on our side we don't reproduce your issue, we successfully display CallKit after receiving `@objc public func pushRegistry(_ registry: PKPushRegistry, didReceiveIncomingPushWith payload: PKPushPayload, for type: PKPushType, completion: @escaping () -> Void) {`.

It looks like yours isn't properly called.
Don't forget to remove all custom implementation (for ex: https://github.com/voxeet/voxeet-sdk-ios/wiki/Manage-push-notification#custom-notifications) so VoxeetSDK's methods can't be overridden by one of yours.

**Comment by iDylanK** [comment]
The sample app gives me the same problem when I add:

```
let info = VTParticipantInfo(externalID: "email@email.nl", name: "name", avatarURL: "")
VoxeetSDK.shared.session.open(info: info) { _ in }
```

So this seems to be the problem. I tried putting it in the AppDelegate and moving it to my first view controller's viewDidLoad, but it gives the same problem. On my server I'm using the 'email@email.nl' to send the invite. How should I set the externalID?

iPhone X iOS 14.4.1
VoxeetSDK 3.1.2
VoxeetUXKit 1.4.4

**Comment by vjard** [comment]
Hello @iDylanK, I tried to reproduce your crash, but I didn't succeed!

I've added `let info = VTParticipantInfo(externalID: "vincent@email.nl", name: "vincent", avatarURL: "")
VoxeetSDK.shared.session.open(info: info) { _ in }` in AppDelegate, but everything works correctly even with the sample app.

Is it possible to send us your full sample without your key/secret to debug it?
How do you invite the other user?

**Comment by iDylanK** [comment]
I'm not changing anything inside the sample app except for adding the `VoxeetSDK.shared.session.open` inside the AppDelegate. 

My server is sending the invite on the frontend using:

```
function invite(conference) {
        const participants = [{ name: "name", externalId: "email@email.nl", avatarUrl: "" }];
        VoxeetSDK.conference.invite(conference, participants).then(() => {});
}
```

```
VoxeetSDK.conference
            .create({ alias: conferenceAlias })
            .then(conference => VoxeetSDK.conference.join(conference, {}))
            .then(con => {
                ...
                invite(con);
            })
            .catch(_ => _);
    };
```

**Comment by VTCoco** [comment]
Ok so your server invites iOS. But is there a live conference to be invited to?
If you invite someone without a live conference, yes you will have some strange behaviours and I can now understand your crash.

(Carthage and VoxeetSDK aren't compatible with xcframeworks for now, that's something are are working on)

**Comment by iDylanK** [comment]
What? The server is creating and joining a conference before inviting the iOS users, right? It all works fine with the iOS app opened... The PushKit is received and a call is shown. After picking up the iOS and browser users are in the conference together...

**Comment by vjard** [comment]
@iDylanK, Can you try to use 2 iOS for this flow? 
User A opens a session, put the application in background.
User B opens a session, creates/joins a conference and after invites User A.

> My server is sending the invite on the frontend using... After picking up the iOS and browser users are in the conference together.

Is server = web page for you?

You can use this official workaround from carthage: https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md

**Comment by iDylanK** [comment]
I'm sorry I meant the web page, not the server. 

With two sample apps running it seems to be working. What do I have to change in my JS implementation to get it working in the browser as well?

**Comment by vjard** [comment]
@iDylanK , it seems that you are not waiting the join response before calling invite.
Try something like this:
```
VoxeetSDK.conference
            .create({ alias: conferenceAlias })
            .then(conference => { 
               VoxeetSDK.conference.join(conference, {}).then((conf) => { ...invite(conf); })
            })
            .catch(_ => _);
```

**Comment by vjard** [comment]
@iDylanK can you confirm that it solves your problem?

**Comment by iDylanK** [comment]
Yes I'll be working and testing later today!

**Comment by iDylanK** [comment]
@vjard @VTCoco  today I finally managed to get it working with some extra adjustments on the webpage. Thanks for your help!
