### ISSUE TITLE
Is this possible to set one view inside Conference call UI?

### ISSUE THREAD

**Issue by Ashish1112** [voxeet/voxeet-uxkit-ios#3]
For more detail you can see below screenshot

Can i add my custom view on red border?

https://user-images.githubusercontent.com/21678840/64686138-cddcc200-d4a5-11e9-847c-3d5a59f7cc9c.png

Thanks in advacne

**Comment by VTCoco** [comment]
Do you just want to replace the text or do you want to add a total custom view inside your red rectangle @Ashish1112 ?

**Comment by Ashish1112** [comment]
I want total custom view inside red rectangle

**Comment by VTCoco** [comment]
Ok, I'm currently working on a solution to fully customize this framework with UX modules. First I need to finish it and I also need to document it so it's not quite ready.

So for now I can advice you to fork this project and modify the `VoxeetUXKit.storyboard` or wait the next version (v2.x).

**Comment by Ashish1112** [comment]
Yeah sure No problem
Once you ready with solution then please let me know so i can configure it

Thanks you so much for your support

**Comment by VTCoco** [comment]
Yes I let this issue opened until its ready :)

**Comment by Ashish1112** [comment]
When i expect from you , it get completed
so i can implement it

Hope you can understand

Thanks

**Comment by Ashish1112** [comment]
Hello,

Any update?
Still I'm waiting for your reply

Thanks

**Comment by VTCoco** [comment]
No ETA for now (as said earlier you can still fork this repo to accomplish your task).

**Comment by VTCoco** [comment]
Hello @Ashish1112, we added a feature to embed top bar, bottom bar, video render, etc as **modules**.
You can pull our latest release to see our code (the storyboard can be a good start to inspect), I think what you were asking is now possible without forking this repository.
