### ISSUE TITLE
Installing VoxeetSDK and VoxeetUXKit with Swift Package Manager

### ISSUE THREAD

**Issue by jiangri927** [voxeet/voxeet-uxkit-ios#30]
Hello. How are you?
Can you make the package for VoxeetUXSDK? I want to use it at SwiftUI

Please give me your guide.
Thanks a lot.
<img width="742" alt="Screen Shot 2022-01-31 at 09 10 23" src="https://user-images.githubusercontent.com/78546492/151808572-bade666c-dcc4-4de5-a7ee-605465e583e5.png">
<img width="425" alt="Screen Shot 2022-01-31 at 09 11 00" src="https://user-images.githubusercontent.com/78546492/151808636-9f4a148d-ca9b-436b-a9df-5c61336b016c.png">

**Comment by alok-think** [comment]
I got the same issue, please fix it asap.

**Comment by FabienLavocat** [comment]
A Pull Request is in progress - https://github.com/voxeet/voxeet-uxkit-ios/pull/37 - we are working on adding the support for Swift Package Manager to the UXKit.
In the meantime, you can install the package using Carthage.
