### ISSUE TITLE
[Request] Adding conference window status (maximized , minimized)

### ISSUE THREAD

**Issue by leojkwan** [voxeet/voxeet-uxkit-ios#4]
When the conference view controller is presented, it takes on the first responder, hiding any message input presently up (ie. chat input bar). It'd be nice to know when the conference view is minimized so an app can display a chat bar back up. I think this would be a great addition to the VTConferenceDelegate. Please let me know your thoughts!

**Comment by leojkwan** [comment]
any help on this?

**Comment by VTCoco** [comment]
Hello, this feature is not yet available but can be interesting.
I will talk with team about the feasibility, however I don't think we will use a delegate for this one, just a getter.

**Comment by leojkwan** [comment]
As long as there is some way to know the changes of the window state!

**Comment by VTCoco** [comment]
For now we don't have a window state but I can give you a work around with this method:

```swift
    func isVoxeetUXKitMinimized() -> Bool {
        if let window = UIApplication.shared.keyWindow {
            for subview in window.subviews {
                if subview.frame.width == 98 && subview.frame.height == 130 {
                    return true
                }
            }
        }
        return false
    }
```

Keep us in touch if this method is enough for your workflow, thank you.
