### ISSUE TITLE
UxCallkit gets frozen when conference.join is called

### ISSUE THREAD

**Issue by feded** [voxeet/voxeet-uxkit-ios#5]
After fetching a created conference, the join method is called and never returns either success or fail. The app freezes. 

Here my peace of code causing the issue:

`
        
            VoxeetSDK.shared.session.open(info: user) {  error in
                   UIApplication.shared.isNetworkActivityIndicatorVisible = false
            
            // Join the conference.
            let joinOptions = VTJoinOptions()
            joinOptions.constraints.video = true
            
            VoxeetSDK.shared.conference.fetch(conferenceID: self.conferenceId ?? "", completion: {
                (conference) in
                
                
                
                
                VoxeetSDK.shared.conference.join(conference: conference, options: joinOptions, success: { (json) in
                    print("Conference joined")
                    
                    // Re-enable startConferenceButton when the request finish.
                }, fail: { (error) in
                    // Re-enable startConferenceButton when the request finish.
                    print("Error on voxeet", error)
                    self.errorPopUp(error: error)
                })
            })
            
            
        }
`

**Specifications**

  - Device: Iphone 6, Iphone 10
  - OS:  13.5.1
  - Platform: IOS

**Notes**
After several tries I can get the join to ask for permissions (video / audio ) and works. Once the permissions where accepted the app seems to go ok afterwards. 

Is there a way to ask for permissions previous a join so I could try to avoid this? 

Thanks.

**Comment by VTCoco** [comment]
Hi, can you manually try to ask microphone/camera permission before joining a conference to see if permissions are related?
(ex: https://stackoverflow.com/questions/24981333/ios-check-if-application-has-access-to-microphone)

**Comment by VTCoco** [comment]
Also, how do you get your `self.conferenceId`? If you want you can use create/join methods with an alias, if the conference is already created it will automatically retrieve conference information and not duplicate it: https://dolby.io/developers/interactivity-apis/client-sdk/getting-started/create-a-basic-audio-conference-application#step-4-add-a-joining-option (see 3. Swift)

**Comment by feded** [comment]
Hi @VTCoco, Thanks for your reply. 
I've tried with a workaround and ask for permissions previously, this reduced the cases of errors but the problem is still there. 
Regarding of how I get the conferenceID? I'm generating the conference on another peer and I using that conference.id form the created conference from where I use the fetch method. 
I've tried with a create instead of a fetch but this made it even a worse case scenario. 
For now I'm keeping the previous video and mic permissions. 

Could the problem be when creating the conference, It may not be fully created on certain cases?

**Comment by VTCoco** [comment]
I not really sure, create should work fine, do you experience the same freeze with the UXKit sample? (https://github.com/voxeet/voxeet-uxkit-ios/tree/master/Sample) <- don't forget to update your key/secret in AppDelegate.swift

When you say a "freeze", is it freezing indefinitely or is it getting better after waiting? Have you log the create/fetch response and join response to see if there is something slow/wrong?

**Comment by feded** [comment]
I was using the UXKit, but at the end I managed to make it work using your Cordova implementation. 

When I was saying "freeze" the UX black screen appeared but the connection was never started. So I had to kill the call/app to restart it. 

Thanks for the support.
