### ISSUE TITLE
「VoxeetSDK.shared.conference.positio」is doesn't work.

### ISSUE THREAD

**Issue by kosukekurimoto** [voxeet/voxeet-uxkit-ios#6]
「VoxeetSDK.shared.conference.positio」is doesn't work.

**Comment by VTCoco** [comment]
Voxeet audio 3D is disabled by default (used by `VoxeetSDK.shared.conference.position`).

If you want to enable it put this line in your AppDelegate:

```swift
VoxeetSDK.shared.conference.audio3D = true
```
