### ISSUE TITLE
support swift 5.3.1

### ISSUE THREAD

**Issue by CHNDarryl** [voxeet/voxeet-uxkit-ios#8]
when i run this code.
Xcode version 12.2(RC):Error
Failed to build module 'VoxeetSDK' from its module interface; the compiler that produced it, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)'
can‘t run.

**Comment by VTCoco** [comment]
Hello, we will release VoxeetSDK v3.0.1 next Monday (16th November 2020) to embed our latest features and Swift 5.3.1 support.

**Comment by MahhmoudFekrySure** [comment]
@CHNDarryl  did problem solved with you
